### ISSUE TITLE
use_modular_headers!

### ISSUE THREAD

**Issue by danish5454** [duguyihou/react-native-turbo-image#230]
`The Swift pod `react-native-turbo-image` depends upon `RCT-Folly.common`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

**Comment by duguyihou** [comment]
hey @danish5454 is this the error showing when `pod install`? If so, it may be related to [this](https://github.com/callstack/react-native-builder-bob/issues/518).
