### ISSUE TITLE
iOS: build issue - Not able to use with "@react-native-firebase/app"

### ISSUE THREAD

**Issue by PrinceUBS** [duguyihou/react-native-turbo-image#255]
<img width="723" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/75003713/20ce240c-0998-4666-aba4-8ed08e843a6c">

Not able to use "react-native-turbo-image" after adding react-native-firebase "@react-native-firebase/app" & "@react-native-firebase/auth" then configuration of iOS & pod-install.

### Versions
```
"react-native": "0.74.2",
"react-native-turbo-image": "^1.4.0",
```

`Xcode Version - "15.4"`

**Comment by duguyihou** [comment]
hey @PrinceUBS can you try one thing? remove `react-native-turbo-image` and keep `react-native-firebase`.  Let's see how it goes

**Comment by ubrainrepo** [comment]
Yes, @duguyihou! I removed `react-native-turbo-image` and able to use `@react-native-firebase/app`.

**Comment by PrinceUBS** [comment]
Yes, @duguyihou ! I removed `react-native-turbo-image` and able to use `@react-native-firebase/app`.

**Comment by duguyihou** [comment]
okay, it may be related to `XCFramework`. I will take a look later. If I cannot make it, I will create a new version with swift source code. Thanks for letting me know.

**Comment by TowhidKashem** [comment]
Might be cause react native fire base requires "use frameworks" to be te to true. In the past I was able to fix comp ability issues by installing the other package as a static lib. Which required a change to the pod file if using expo via a config plugin otherwise directly. If that's the issue here, I guess the question is can turbo image be installed as a static lib..

**Comment by duguyihou** [comment]
@PrinceUBS 
I used RN 0.73.6 in the example app and can build it successfully with Xcode 15.4. I don't use `react-native-firebase` but it should be fine. The change is on [this branch](https://github.com/duguyihou/react-native-turbo-image/tree/255-ios-build-issue-not-able-to-use-with-react-native-firebaseapp). I will do more testings and create a new release if everything is okay.
<img width="1053" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/9347790/758e6f19-16c1-405c-896e-6f9f31260445">

**Comment by PrinceUBS** [comment]
Working like a charm✨! Thanks @duguyihou!!

**Comment by duguyihou** [comment]
@PrinceUBS I created a new release. Let me know if you still have this issue
