### ISSUE TITLE
upgrade example to the latest

### ISSUE THREAD

**Issue by duguyihou** [duguyihou/react-native-turbo-image#264]

**Comment by Gautham495** [comment]
Is this library an alternative to fast image? Will it be available for the new arch and if yes when?

Just wanted to say - Awesome work and this library is an awesome alternative to fast image.

**Comment by duguyihou** [comment]
hey @Gautham495 
- Yes. Turbo Image is aimed to be an alternative to fast image. It already support the new arch. See the video. You can install it and give it a try.
- I did not encounter memory cash when using it. 

This ticket is to update example. 

https://github.com/duguyihou/react-native-turbo-image/assets/9347790/39eef541-a127-4b41-98ab-f4019320aafe

**Comment by Gautham495** [comment]
Nice. Why does that flicker happen when the image moves from placeholder to normal image.

**Comment by duguyihou** [comment]
I guess the flicker issue is because fade duration only works for the image, not placeholder. 
Most of the props are similar to fast image. During the implantation, I followed the naming conversion of Nuke. 
Regarding to animated, I have not thought about it. 😃

**Comment by duguyihou** [comment]
@Gautham495  This is the lib test project. https://github.com/duguyihou/APPLibTest

**Comment by Gautham495** [comment]
Let me know if you can get this working in yout library. I will change out fast image with yours this coming week.

https://github.com/DylanVann/react-native-fast-image/issues/89#issuecomment-347210412

**Comment by Gautham495** [comment]
Hey, @duguyihou When I tried to install the library - I am getting this Unsupported Swift architecture

<img width="261" alt="Screenshot 2024-07-10 at 10 22 28 PM" src="https://github.com/duguyihou/react-native-turbo-image/assets/50621157/e1b18228-e239-4945-bdd5-1fa798029bff">

I am using React native version 71.0

Let me know

**Comment by duguyihou** [comment]
@Gautham495 can you provide more information?

**Comment by Gautham495** [comment]
I tried to install turbo image and did pod install. When i tried to run the app its not working and showing this error. Let me know how to fix this.

Is there any native configuration to be done in ios and android.

**Comment by vokhuyetOz** [comment]
you should upgrade your xcode to newest version. It may caused due to swift compatibility

**Comment by duguyihou** [comment]
@Gautham495 I tried it on RN 0.71.0. It works on my side. https://github.com/duguyihou/turboImageDemo

if you think it is a library issue, can you create an example to reproduce it?

**Comment by duguyihou** [comment]
I got build errors when enabling new arch in Android. It seems that it is related to `react-native-screens`. 
<img width="1180" alt="image" src="https://github.com/duguyihou/react-native-turbo-image/assets/9347790/de75e152-8f09-42e4-8565-658533f1c0e1">

However,  [ApplibTest](https://github.com/duguyihou/APPLibTest) works with `react-native-screens`. Then I tried to init a clean lib project with `react-native-screens` and got the same errors. The issue may be that `create-react-native-library` does not like `react-native-screens` under Native components. 

I will close this ticket and try `Fabric view with backward compat`. But I hate Objective-C. 😢 

@Gautham495 please create another issue if you can reproduce it.

**Comment by Gautham495** [comment]
@duguyihou i think if you can make it work for both architectures it would be the best of both worlds.

**Comment by Gautham495** [comment]
Also i think my swift issue is with outdated pods. Can you share me your pods and ruby versions.

**Comment by Gautham495** [comment]
Getting same issue. But I am on XCode 15.2 with Swift 5.9.
 
What version do you use ? @duguyihou @vokhuyetOz So i can upgrade
