### ISSUE TITLE
[Feature Request] Placeholder with fade

### ISSUE THREAD

**Issue by sleeper-seth** [duguyihou/react-native-turbo-image#271]
When utilizing placeholders, thumbhash specifically, the fade duration feature results in a visually unpleasant "flash" when the placeholder is removed and nothing is briefly rendered before the animated fade transition occurs.

While this is manually controllable by turning off the fade, this feature request is to provide a smooth, animated transition between the placeholder display and the final image.

If this is not feasible, I would also suggest that if a placeholder is provided; the fade duration defaulted to 0 unless manually supplied by the end user. That way, the default experience is reasonable, if not perfect.

**Comment by duguyihou** [comment]
hey @sleeper-seth I noticed this behaviour as well. I will look into it later. Thanks.

**Comment by duguyihou** [comment]
@sleeper-seth Does it look better?

https://github.com/user-attachments/assets/16cb4db6-50d3-446f-8f9b-024d544f2992

**Comment by sleeper-seth** [comment]
Looks good 👍
