### ISSUE TITLE
is it possible to Override global imageLoader?

### ISSUE THREAD

**Issue by vokhuyetOz** [duguyihou/react-native-turbo-image#272]
**Is your feature request related to a problem? Please describe.**
it would be useful if we can register all components (decoders) at initialize instead of add it manually when load ImageURl.
use this one we can remove format property.

**Describe the solution you'd like**
have no idea now?

**Comment by duguyihou** [comment]
To be honest, I don't know the performance if we register all decoders. From my understanding, the aim of Nuke or Coil is to handle image loading and caching. Supporting special formats is a bonus.  Even though Coil officially provides extensions for Gif and SVG, we still need to add it manually. For Nuke, it does not provide decoders officially. Besides, not all the apps need special format images. Let me know your thoughts 😄

**Comment by vokhuyetOz** [comment]
i checked on [coil/image_pipeline/](https://coil-kt.github.io/coil/image_pipeline/), it said ```Custom components must be added to the ImageLoader when constructing it through its ComponentRegistry```. So i think it will not cause performance problems. 
of course we don't need to add all decoders to imageLoader by default, but if we can ask library to add some specials decoder as we want in initialize, it would be great. Sometimes, we don't know if our image is Gif or normal type.

**Comment by duguyihou** [comment]
yeah, I agree. It may be silly to set format manually. It is not elegant.

**Comment by duguyihou** [comment]
@vokhuyetOz 

maybe we can use `newBuilder` in Android side.

<img width="710" alt="image" src="https://github.com/user-attachments/assets/7fd00031-bb83-49f6-881e-4cea18911978">

**Comment by vokhuyetOz** [comment]
Ok, I see
I'll check it out at the weekend
