### ISSUE TITLE
getSize method/callback support

### ISSUE THREAD

**Issue by lego-sharat** [duguyihou/react-native-turbo-image#278]
**Is your feature request related to a problem? Please describe.**
I am currently using react-native Image component. In the project we are using Image.getSize method. This is being used to render images coming where we only have the url and not the width and height. We use this to get the current aspect ratio, we are using Image.getsize currently to appropriately render the image. This causes a content shift but that is a tradeoff we are ok with.

**Describe the solution you'd like**
A callback which triggers when we get the actual width and height of the image

**Describe alternatives you've considered**
I haven't't found this in any other library

**Additional context**

**Comment by duguyihou** [comment]
Thanks for raising this. According to the [docs](https://reactnative.dev/docs/image#getsize), does `prefetch` work? Currently, `getSize()` is not in high priority.

**Comment by Vrunalbenke** [comment]
@duguyihou Any Plan for adding this feature - getSize and getSizeWithHeaders
