### ISSUE TITLE
borderWidth not working on Android

### ISSUE THREAD

**Issue by Hot-key** [duguyihou/react-native-turbo-image#284]
**Describe the bug**
On Android, the borderWidth style property does not have any effect on images. 
The border is not visible even when specified in the style.

**To Reproduce**
1. Clone the repository: https://github.com/Hot-key/turbo-image-test
2. Install dependencies: yarn install or npm install
3. Run the app on Android: npx react-native run-android
4. Observe the image without a border

**Expected behavior**
The image should display with a 5-pixel wide black border.
```tsx
function App(): React.JSX.Element {
  const backgroundStyle = {
    backgroundColor: '#fff',
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <TurboImage
        source={{
          uri: 'https://dummyimage.com/300x300/ff0000/fff',
        }}
        style={styles.image}
        fadeDuration={0}
        rounded
        borderRadius={150}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  image: {
    width: 300,
    height: 300,
    borderWidth: 5,
    borderColor: '#000',
    borderRadius: 150,
  },
});
```

**Screenshots**
![image](https://github.com/user-attachments/assets/d339fd8c-e839-447b-b0c8-7651de4df3c6)

**Smartphone (please complete the following information):**
 - Device: iPhone se(emulator), Galaxy S20 FE
 - OS: ios 17.5, android 13
 - Version: react-native(0.74.4) react-native-turbo-image(1.9.0)

**Additional context**
- This issue is only observed on Android. The same code works on iOS.

**Comment by duguyihou** [comment]
hey @Hot-key Thanks for raising this issue. I will release a new version to fix it.

**Comment by duguyihou** [comment]
![simulator_screenshot_A3F989B1-505B-4DF8-8B6A-112143711CB0](https://github.com/user-attachments/assets/d9ae59d6-7721-414a-9ea0-9d1aa4d31eca)
![Screenshot_20240801_203640](https://github.com/user-attachments/assets/6482c5ac-5851-40e2-8c19-4233f98b80d1)

**Comment by duguyihou** [comment]
I will remove `borderRadius` as it makes me confused as well. You just set `borderRadius` in `StyleSheet`
<img width="411" alt="image" src="https://github.com/user-attachments/assets/8b16b233-f684-426a-8084-547505c4ab4e">
