### ISSUE TITLE
Empty image for local IOS image file

### ISSUE THREAD

**Issue by samuelgja** [duguyihou/react-native-turbo-image#285]
**Describe the bug**

Idk if this is an issue or it just not work, but when source is local file on ios, it not work.
note: I did not test android

**To Reproduce**
When source is local ios image in format: `ph://20C6B995-C580-4484-AA9B-BA3F6C198835/L0/001` I get empty image.

**Expected behavior**
It should work even for local image uri-s? Idk

**Smartphone (please complete the following information):**
All ios devices (simulator  / real device), android was not tested.

**Additional context**

**Comment by duguyihou** [comment]
It does not support this format.  You can only load local asset in this way.
```ts
// local asset

<TurboImage
  source={require('../../assets/local.png')}
  style={{ width: 300, height: 300 }}
/>;
```
