### ISSUE TITLE
Crash app trying to load image in Android

### ISSUE THREAD

**Issue by ng-ha** [duguyihou/react-native-turbo-image#286]
**Describe the bug**
Crash app trying to load image in Android

**To Reproduce**
 <TurboImage
        source={{
          uri: 'https://sample-videos.com/img/Sample-jpg-image-5mb.jpg',
        }}
        style={{width: 300, height: 300}}
/>

![Screenshot 2024-08-01 at 17 28 46](https://github.com/user-attachments/assets/ec6d3666-b435-4193-a170-48aef7c67d07)

**Comment by duguyihou** [comment]
hey @ng-ha , it crashed on my side as well. As the error you attached, the image is too large. 
<img width="375" alt="image" src="https://github.com/user-attachments/assets/d6b2b33c-c966-4e88-a4a6-13e74f560506">

Loading a large image will consume more memory. So it makes sense to me when the app crashes.
Try `resize`, it will help you to reduce the memory.
```ts
      <Card
        source={{
          uri: 'https://sample-videos.com/img/Sample-jpg-image-5mb.jpg',
        }}
        style={{ width: 200, height: 200 }}
        resize={200}
        onStart={handleStart}
        onSuccess={handleSuccess}
        onCompletion={handleCompletion}
        placeholder={{
          blurhash: 'UBIr4u9}00Rj?yEzxu%LIQ%1%6xt-ks,tAIU',
        }}
      />
```


https://github.com/user-attachments/assets/25ff9b98-c79f-43e2-bba8-3a8f986d42f4

**Comment by duguyihou** [comment]
btw, I also tried the `Image` which is provided by `React Native`. It crashed.
<img width="930" alt="image" src="https://github.com/user-attachments/assets/6683e5d4-fb47-403c-87bf-9179ccb44a84">
```ts
      <Image
        source={{
          uri: 'https://sample-videos.com/img/Sample-jpg-image-5mb.jpg',
        }}
        style={{ width: 200, height: 200 }}
      />
```

**Comment by ng-ha** [comment]
@duguyihou i tried the `Image` by `React Native`  version 0.74.3. It didn't crash in Android.

```tsx
 <Image
        source={{
          uri: 'https://sample-videos.com/img/Sample-jpg-image-5mb.jpg',
        }}
        style={{width: 5200, height: 5200}}
        onLoad={e => console.log(e.nativeEvent)}
      />
```

```
{"source": {"height": 1691, "uri": "https://sample-videos.com/img/Sample-jpg-image-5mb.jpg", "width": 1268}}
```

It seems like `Image` automatically scales the image down to avoid crashing. Maybe, can you consider to implement this feature too?

Btw,  the `resize` prop worked!

**Comment by duguyihou** [comment]
@ng-ha interesting, the version of RN in the [example ](https://github.com/duguyihou/react-native-turbo-image/blob/0fc6eb89f80fa9c80a58bb1c4597214b157d2609/example/package.json#L16)is `0.73.6`. And yes, I will think about this feature later. But my current plan is to re-write `TurboImage` with `fabric component`. It supports the New Architecture because of Interop layer.

Do you mind closing this ticket if your problem got solved?
