### ISSUE TITLE
Local asset Image not shown in Android in Release mode

### ISSUE THREAD

**Issue by ng-ha** [duguyihou/react-native-turbo-image#292]
**Describe the bug**
Local asset Image not shown in Android in Release mode. In Debug mode, it works fine! Error: `Unable to create a fetcher that supports ... (link asset image)`
Tested in [example](https://github.com/duguyihou/react-native-turbo-image/tree/main/example).

**To Reproduce**
```
npx react-native run-android --mode release
```

**Screenshots**

https://github.com/user-attachments/assets/02d055ef-8098-4a22-9a92-c287bb655cd5

**Smartphone (please complete the following information):**
- Emulator

**Comment by duguyihou** [comment]
@ng-ha 
I will take a look this week. Thanks.

**Comment by duguyihou** [comment]
@ng-ha 
RN image uses `fresco` in Android, which supoorts `res:` uri. Maybe write a custom fetcher or remove local asset support as we can still use RN image for local asset.

**Comment by ng-ha** [comment]
@duguyihou  Local asset images work fine on IOS. Removing it might be a waste ..

**Comment by duguyihou** [comment]
@ng-ha 
I will polish the code this weekend. 😆 
<img width="733" alt="image" src="https://github.com/user-attachments/assets/4c736da3-b8b6-4ca3-9860-a2e0b9aee0ce">

**Comment by ng-ha** [comment]
@duguyihou That's nice. Thank you! 🎉 💯 🔥

**Comment by duguyihou** [comment]
@ng-ha 
I will create a new release and close it, let me know if you still have this problem
