### ISSUE TITLE
What is the performance benchmarks between fast image vs turbo image?

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#301]
I am gonna try this package next week by completely replacing fast image and upgrading my react native app. What are the performance metrics between fast image and turbo image.

The app is image heavy as well. 

Please let me know with demos. 

Because I do not want any random crashes. 

If the migration is a success I will make a full blog post on this awesome library.

Migration will be from: React Native version 71.0 - 73.8.

Thanks!

**Comment by duguyihou** [comment]
Thanks for your input. Unfortunately, it does not align with our current project goals. Closing it.

**Comment by Gautham495** [comment]
No problem. Thanks for making the awesome library.
