### ISSUE TITLE
Ability to animate turbo image like fast image.

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#306]
I had a animation function with fast image which goes like below.

```ts
const AnimatedFastImage = Animated.createAnimatedComponent(Fast);
```

and it worked. Like i use it to scale up and down the image which gives a nice animated feel when users enter a screen.

```ts
const AnimatedTurboImage = Animated.createAnimatedComponent(TurboImage);
```

The animations do not work properly for turbo image but other features work flawlessly.

Let me know if you could add this feature. It will be a nice addition. If this is done please add it to the docs/ReadMe so people can use it as well.

**Comment by duguyihou** [comment]
@Gautham495 

Can you try `v1.12.2` ? let me know the result. Thanks.

**Comment by Gautham495** [comment]
Working perfectly. I tested in ios now. But should test in android.

**Comment by Gautham495** [comment]
Is there any other way i can dm you lol. I am going to replace fast image with your library completely.😇🗿. What about the linear gradient library? I want to use it for easing gradients and grayish gradient replacing blur views.

**Comment by duguyihou** [comment]
I don't use Twitter or X. Do you mind closing it since it works with `react native reanimated`?

**Comment by Gautham495** [comment]
Closing this as its working. Please add this to the docs to make this the ultimate library with animated support🐐
