### ISSUE TITLE
Gif from Giphy is not working. (Tested in iOS for now)

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#311]
Everything works properly with the superior loading and caching.

But when i tried to load this giphy gif : https://media0.giphy.com/media/FQnQxbIs10v1qkObS4/giphy.gif?cid=0c6ce8f6t6gzbc51lhpilimdjlvaz5969zkc072hb87stzp3&ep=v1_gifs_search&rid=giphy.gif&ct=g. Only the first frame is showing and the gif is not playing and is stuck.

Tested only in iOS. Please check this issue and fix it if possible.

Thanks @duguyihou.

**Comment by duguyihou** [comment]
@Gautham495 

 Can you show me the code and the url of the gif? To me, the link above is not a gif url.

**Comment by Gautham495** [comment]
Thats strange. Giphy has different types of urls. I switched to normal Image and it worked. If i come across proper usecase in my app I will reopen this issue. Closing it for now. 

Thanks for the support.
