### ISSUE TITLE
Android Crash: Error While updating property 'resizeMode' of a view managed by: TurboImageView

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#312]
I got a crash in android stating: Error While updating property 'resizeMode' of a view managed by: TurboImageView.

  <TurboImage
        source={require('../../Assets/IMG.webp')}
        style={styles.bg}
        resizeMode="cover"
      />

Above is the code sample.

**Comment by duguyihou** [comment]
@Gautham495 

It works on my side. Can you create a example app to reproduce it? 
<img width="914" alt="image" src="https://github.com/user-attachments/assets/a1e125d5-8bd8-4159-8099-8dc3b209a6c4">

**Comment by Gautham495** [comment]
Actually it happened in here only where i passed a boolean value directly to the source. FastImage handled it but i think turbo cannot and I should split to 2 different components and not split the source itself. Both are remote uris.

<TurboImage
            source={{
              uri: someBoolean ? image1 : image2,
            }}
            style={{
              width: someBoolean ? screenWidth * 0.1 : screenWidth * 0.13,
              height: someBoolean ? screenWidth * 0.1 : screenWidth * 0.13,
              zIndex: 1000,
              borderRadius: 10,
            }}
            resizeMode="cover"
          />

**Comment by duguyihou** [comment]
okay, maybe enhance it in the future. Closing it.

**Comment by Gautham495** [comment]
Yes thanks. Will keep this in mind when making future components with turbo image.
