### ISSUE TITLE
Android crash with com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'source' of a view managed by: TurboImageView

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#318]
This log is captured by Sentry when using turbo image 

"com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'source' of a view managed by: TurboImageView\n\tat com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyC...

Let me know how to fix this.

This is happening only in Android and not in iOS and its crashing here and there which is not ideal.

**Comment by Gautham495** [comment]
@duguyihou

**Comment by Gautham495** [comment]
This issue is happening only due to the local image integration. So I think turbo image should not be used with local images so these crashes can be avoided then.

**Comment by Gautham495** [comment]
Plus - In iOS the caching takes place flawlessly but in android, the images get loaded everytime when the state/ when the user enters the screen.

So these are my observations in a production app.

**Comment by Gautham495** [comment]
Plus this happens when codepush is installed in the android side of the react native app. So when a new codepush update is done - Android app shows ANR issue and crashes.

**Comment by Gautham495** [comment]
Yes. For the remove images, its not crashing this. Please update this in the docs. I have the speed to update in 100+ files. If others updated it with local assets and pushed it to production without testing it will be tough to debug later.

**Comment by Gautham495** [comment]
Ok i changed all the local images from turbo to RN and moved from images to the remote url then the flickering and crashes in android is solved.

Please please - Add this in docs.

**Comment by duguyihou** [comment]
@Gautham495 

- Thanks for your input.
- For my current testing, app will crash in release mode when loading local `svg` files. I already mentioned that supporting special format is only for remote urls. 
- I will try to fix it later. Otherwise I will remove local asset support to keep TurboImage in a small scope.

**Comment by Gautham495** [comment]
Yes for remote urls, this is the best stand in replacement for fast image. But it crashes for local images in android.

I have successfully integrated this library fully into my app. @duguyihou
