### ISSUE TITLE
Issue where if the image is loading and user navigates to other page/screen - the image is stuck without full completion if blurhash is used - Tested in iOS but no problem in android

### ISSUE THREAD

**Issue by Gautham495** [duguyihou/react-native-turbo-image#326]
### What's happening?

As said in the title, this is a real application where - the user will move from a screen to another within seconds and if he comes back to the same screen the unloaded images are stuck in blurhash state only.

This happens only in iOS.

Also the images get loaded again and again if url cache is used. But in fast image - the is always loaded and there is no indication that image has been refetched. But here the blurhash happens often which means the image is being loaded again and again if accessed after sometime which is not a case in fast image.

Let me know how to fix this.

The library i use for navigation is react native navigation.

### Reproduceable Code

```tsx
Its the normal code from example
```

### Relevant log output

```shell
No logs
```

### Device

iPhone 12 - 17.5

### TurboImage Version

1.13.0

### Can you reproduce this issue in the TurboImage Example app?

Yes, I can reproduce the same issue in the Example app

**Comment by Gautham495** [comment]
@duguyihou - In android the reloading does not happen - but in iOS the image is not cached longer.

**Comment by duguyihou** [comment]
@Gautham495 

Can you send a video here to the cache does not working in iOS?

**Comment by Gautham495** [comment]
I will try with the memory cache by removing the blurhash by upgrading to 1.16.0. Is it a better solution than current ones?

**Comment by Gautham495** [comment]
ok using the dataCache fixed this.
