### ISSUE TITLE
custom cache key for uri source 

### ISSUE THREAD

**Issue by Splicer97** [duguyihou/react-native-turbo-image#328]
### What feature or enhancement are you suggesting?

Is it possible to add custom cache key for uri source. For example, I have s3 image bucket with dynamic source, but I have unique ID key from server and I want save and get image by this id

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Like alternative I use react-native-blob-util for download image with dynamic link, save and check this image in filesystem by uniq ID from server

**Comment by duguyihou** [comment]
@Splicer97 

thanks for your input. I am not sure if we can do that. I will think about it and get back to you later.

**Comment by duguyihou** [comment]
@Splicer97 

Is this what you want? In iOS, I passed `cacheKey` to override the image identifier used for caching and task coalescing.

```ts
      <TurboImage
        source={{
          uri: item.uri,
          cacheKey: `CacheKey+++++++++${item.uri}`,
        }}
        style={styles.card}
        resizeMode="cover"
      />
```

https://github.com/user-attachments/assets/6da178d5-af9e-4c7f-a705-3d6a2d003d80

**Comment by Splicer97** [comment]
So, can I use custom cache key on cacheKey ite in source prop? It works for ios and android both?

**Comment by duguyihou** [comment]
yes, this is the draft. The `cacheKey` is used to query and store the image. If not provided, the `uri` is used also as the cache key.

> Like alternative I use react-native-blob-util for download image with dynamic link, save and check this image in filesystem by uniq ID from server

Can you explain this in detail? TBH, I don't understand the use case.

**Comment by Splicer97** [comment]
> yes, this is the draft. The `cacheKey` is used to query and store the image. If not provided, the `uri` is used also as the cache key.
> 
> > Like alternative I use react-native-blob-util for download image with dynamic link, save and check this image in filesystem by uniq ID from server
> 
> Can you explain this in detail? TBH, I don't understand the use case. I don't know how it works.

Okay, thanks. Now I fetch image by blob util library, I save image by cache Key in file system and then check, if I already have this image in file system by this key, I add this image in Image component

**Comment by duguyihou** [comment]
> Okay, thanks. Now I fetch image by blob util library, I save image by cache Key in file system and then check, if I already have this image in file system by this key, I add this image in Image component

I implemented `cacheKey` following [expo-image](https://docs.expo.dev/versions/latest/sdk/image/#imagesource). Now that you can fetch image from disk via the key, that should be fine. Is it because of S3 image bucket that you cannot get the url directly?

**Comment by duguyihou** [comment]
@Splicer97 

`cacheKey` is in v1.17.0. https://github.com/duguyihou/react-native-turbo-image/releases/tag/v1.17.0
Closing it.

**Comment by Splicer97** [comment]
> @Splicer97 
> 
> `cacheKey` is in v1.17.0. https://github.com/duguyihou/react-native-turbo-image/releases/tag/v1.17.0
> Closing it.

Thank you!!!
