### ISSUE TITLE
bug: IOS does support displaying local image in 1.17.1

### ISSUE THREAD

**Issue by MS0015** [duguyihou/react-native-turbo-image#341]
### What's happening?

It showing gray box after updating to latest version
<img width="260" alt="Screenshot 2024-09-06 at 12 52 33 AM" src="https://github.com/user-attachments/assets/3c92cde6-3dfd-47c3-9206-a165e4075646">

### Reproduceable Code

```tsx
<TurboImage
        tint={COLOR.GRAY}
        style={{
          position: 'relative',
          width: 22,
          height: 22,
          marginHorizontal: 4,
          ...iconStyle,
        }}
        source={iconSource}
        resizeMode={'contain'}
      />
```

### Relevant log output

```shell
no
```

### Device

iPhone xs

### TurboImage Version

1.17.1

### Can you reproduce this issue in the TurboImage Example app?

No, I cannot reproduce the issue in the Example app

**Comment by duguyihou** [comment]
It is not a bug. We removed local asset support since 1.15.0. https://github.com/duguyihou/react-native-turbo-image/releases/tag/v1.15.0

**Comment by abathz** [comment]
hi @duguyihou 👋🏻, im currently using version 1.17.2 and using local assets in my project.

i want to know why you dropping local asset support?

thank youu!

**Comment by abathz** [comment]
> @abathz
> 
> #324

ahhh thanks!!👍🏻
