### ISSUE TITLE
bug: resizeMode behaves differently in Android and IOS with GIF format

### ISSUE THREAD

**Issue by ng-ha** [duguyihou/react-native-turbo-image#342]
### What's happening?

resizeMode behaves differently in Android and IOS with GIF format

### Reproduceable Code

```tsx
<TurboImage
        source={{uri: "https://private-user-images.githubusercontent.com/115610452/365133983-03664cbe-6e80-43ab-9432-86b938419d3e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTkzNDIsIm5iZiI6MTcyNTYxOTA0MiwicGF0aCI6Ii8xMTU2MTA0NTIvMzY1MTMzOTgzLTAzNjY0Y2JlLTZlODAtNDNhYi05NDMyLTg2YjkzODQxOWQzZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMDM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjc3YTg3M2YxYmJlYzBjMzcyODFlYmJiZTNmNWRjZmZlZGRjNWQ5Mzc3NWE1NjJhYjVjOTMzMzU3MTQ3Njg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ub8FzrVUDDao_qIdjQAG0cfRxDtNjy1S3DNLdpZt5Gc"}}
        format="gif"
        resizeMode="contain" // or other modes
        style={{width: 200, height: 52, backgroundColor: 'red'}}
      />
```

Here is the image: 
![f14956ae5657af89dea206f279e81024ade909a7e0489b7ad646f44eea2beff4](https://github.com/user-attachments/assets/03664cbe-6e80-43ab-9432-86b938419d3e)

### Relevant log output

Strech:
![strech](https://github.com/user-attachments/assets/dd3174ef-a715-487a-b3c7-d9848eb846d1)

Cover:
![cover](https://github.com/user-attachments/assets/4530ea42-bd6e-4fc0-ae96-444f097ca553)

Center:
![center](https://github.com/user-attachments/assets/7d330174-072a-4df3-a042-da41a3596dd9)

Contain:
![contain](https://github.com/user-attachments/assets/a53c1aa6-0b29-412b-ab9d-1251b7f7ed06)

### Device

iPhone 15

### TurboImage Version

1.13.0

### Can you reproduce this issue in the TurboImage Example app?

Yes, I can reproduce the same issue in the Example app

**Comment by duguyihou** [comment]
<img width="629" alt="image" src="https://github.com/user-attachments/assets/d6ac24c5-0545-4c99-9c48-68e5da56d8d3">

The url does not work for me. I will try to reproduce it with one of the urls in the example

**Comment by duguyihou** [comment]
@ng-ha 

seems it happens to all the images no matter gif or not
<img width="659" alt="image" src="https://github.com/user-attachments/assets/39a58ba4-dff0-4d8d-933a-42667b97aea6">

**Comment by ng-ha** [comment]
@duguyihou i did set resizeMode in Reproduceable Code

**Comment by duguyihou** [comment]
@ng-ha 

- Yes, the `resizeMode` behaviours are different in two platforms. To me, it works in Android while it always `stretch` in iOS.
-  I just found another issue related to `resizeMode`.

**Comment by duguyihou** [comment]
@ng-ha 

The root cause is `contentMode` is always `scaleToFill` in iOS. We use `Gifu` to handle gif image. will check it later if we can fix it in our code.
<img width="742" alt="image" src="https://github.com/user-attachments/assets/6b2f96d2-a044-4eb7-8748-f67c59b5995d">

**Comment by duguyihou** [comment]
@ng-ha 

![Xnip2024-09-13_07-10-39](https://github.com/user-attachments/assets/371a0f67-8d74-4f0d-b637-2f5fd3183c12)
![Xnip2024-09-13_07-11-21](https://github.com/user-attachments/assets/0b259a2e-10c1-4400-9ca4-38938a64ab96)
![Xnip2024-09-13_07-12-54](https://github.com/user-attachments/assets/0d18fa83-f51a-444f-ac7c-115469c4dbd3)
![Xnip2024-09-13_07-15-06](https://github.com/user-attachments/assets/7e506386-b6a5-4eeb-8799-f1cbaa3f66d7)
